apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYU5jWlM3VjBlUzB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1qSXhNalV4TXpCYUZ3MHpOakF5TWpBeE1qVTJNekJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM4TGtpbVJyOU5UaGNwbmlGaDBaQ055SGpObnBmbnEzMDJXclg2VG1CYkNPMXQ4VXFjVmYyYzArZEoKWWI1Ni80R2ZDenhDTDJXMVRWVEpEaGs4ejE2eXNGa09oc2sxbXN5dkxGbjhDWURNMHNlZUZWaFRXc0MxYWk4QwpzMXlPNjZFRW5nODdUMzFJaUFGdmF6azJnb1ZreTBRR2U5aS85K1ZDUFVqZU0vQmY4RWdoZ3pMdSt1WjhFY21CCjVIRkI3YzluaW5PdWZEOHpZNmJXQTAzNzlVUVZ4ekFDLzI3UEp6eTM1d3dHNUljOEdFZUcvZWhyNVU3NGNTaEUKamF0c2xjVWJzVWR0cTd3dFZNUnByaUhuRnMxbVQ0aWRUK2V2S2hTYkZUSklnQjlacWwra3hxUWdzeWtpQ1hWYgpNWU4yNVk0RkFCQUtlZXJwTG9ja2R2WEhUUWgxQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRM2p4OHhpQUFZM0FLZm1sUTRndmFwWS9aSkREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTJiUTZWdjhSVQpUUXRDZm5VRGhpeDc2bnVpZmIyd0oxbXhhdlRpRHB3dGUvT0hBTDFLbmdjZnV2SW1CK0k5SUNVVE1VamFuUHc2Ck9Lbk5admc1akhRR3YwcFZYeDI4ZUFCbFRzVVEyVXJXWDFGWEx4YmlNZXBIVjcrNEIzdWJmWXAwS0NUdVNGSWcKcEtnSkFzeE9SMjFMN0xjcWxudU53bm8wNUFBNmFEdWJ5U0g1OW1ESGt6Z2wybm1ic2hoS3ZuVzdGL1hPcG5XNgpRdlV3WlVGZmlqS2NYUzVUTGp0M0Ivek4xdlhvTGxmdUZKZjFwbUZLczNtQjdpNFozVHlIYjdwanZNNHJCZ0JvCjUwVGxML21OZlp4TTRFSXpUdFF0cFh1U3NHSGd3N3dqZ05XWXBNZDFBRUtvTHlWRVVCRXVYSjdTK0MzQzROdUIKdUdSOVE4RGJpMHRQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://72FB7EE3B0AA53877E6D5CBED06E1A6D.gr7.ap-south-1.eks.amazonaws.com
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: /usr/bin/aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "demo-cluster"