
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWW4vR2c4N1hkNTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1ESXhOelF6TlRWYUZ3MHpOakF4TXpFeE56UTROVFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM3M1ZCVTR0d25ZeWoydW1BdXdTUEEzRnpMaThzRVh2U1p3SitjYitHbWx0Znh2MU42bjVuNGE5LzcKeEQ5QS9HR2FzUTU2T0xjaW5UV2Q2REJ3UGk0Tklrb0l0UWNRVnZ1VlpaL3lkczVucWhxM0RINTVzMmpCTXVsRwpGdm01Nk95MWZDcEQ1NXdXNG5uZmx4bVZTZ1MzemdRTjJORzNMdkE5akVkREdQVlM0S05UUDFXS0NydGkzU3VtCmkzcUw5NmJCTTVjc05naExubVZPaHp6SjJ0SWVTSjNtcTJ4VzA3d2xqM2J2Um5UdjRMYng0SUlVd2tySHpiMkoKeDV0M3cwV0dOTTlDcXVBMzI1QjJhMGtIbitmdUZBK1Zld3RLdlBwVUxuVXYwWjhPN1o3RUZoZkttQnlEVzQ0NQphUGcwMkswSHFMU3A4UnB4c0xybDVDek43ZzdWQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSanpjTDV1T0dtUWlhWTZLY0RRMUxKWCsvdTh6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0hjRnh4Z01WdQo1ZzA1R25RZG1RMXBNc0M5bVJNc2hQZDROV1FNeUo1TkxlMURYK21LREhPV09CZjJtWG54T2ZGMDdxYUZ0SGZ6CnhTUTNYZVl4TUgyYklkTFBiUkUwTmJvSDJqU3loYXJXUW5TT2RCakp3OG9BRkE1QTJtZiszK3FEQ0daN2IvckoKbVk0a0cyVmFWTlZXd2huOEtYdVhFMk12V0UwVjdUR2NxR2RnQVFjTXpONWtocnUxeHI2V2ZQWHVvSDUvbXBHQgozYW10MjMzU0NNbitwL3pkQjU3eTFsa0kwTlVUckp4MEtLWWVDc3NIMG1ZOTR0WENhNkdJWTVNd1N3WnYzZXBYCmFCQU5zRnltT1NxdkxqYnZwa04zdXN5dlhsRlNOaExRbDdidldUOWJPN3hGaGNoQ3RIT0RvVHBVd2ZFMWMrLzUKVkNCU2xiU2VGWFNwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://82503549-a5ed-4003-8ee7-2f060abead8a.ap-west-2-gw.linodelke.net:443
  name: lke563826

users:
- name: lke563826-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InpfSlNGdTk3TzJyUXRRNGdnc2RqdkRjRkpLSVltODE3QjlfbURfa1pxbTQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbms2YjYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiM2Y5NDViY2ItZTVlNi00MmQ5LThkZGQtODQxNjllYWI1NWJiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.ridX5Tw7nBrpuAXdBgiJO1nZ3ERCk7_aEO5rfRFAJDCXSIdSMZUUBNU0rWpR0zFogMbCvrtW1lcHHsN0sI8twZyJTnUklvDGn9fVAPvp2GLz3Zhr0i5cnLdAQPuG0zXKAhQRbYrL8uveb5QmcmRMldQdEfDa4TIoNhnf63Of7ojaQhNm68CU28NxtyKN-sL4SbwyVBsn9nTd9xHCfiI7iyES8lEH8hfuqamIzkphzLs9ZUv80LgZd6N8AvDrqerBwYq7MmdH9M0rfFNQBvU9l8MVdLJKYcfEBLWsperHrkP9bSbihiJFyvPhzh8jUmtML5kmU1IMkZoRtF_N6qcQVQ

contexts:
- context:
    cluster: lke563826
    namespace: default
    user: lke563826-admin
  name: lke563826-ctx

current-context: lke563826-ctx
